import re

context_templates = {
    "Snoopy": [
        "A beagle lying on top of its red doghouse, gazing at the clouds in {} style.",
        "A cartoon dog imagining itself as a World War I flying ace, rendered in {} style.",
        "A white dog with black ears typing on a small typewriter atop its kennel, in {} style.",
        "A yellow bird perched on the nose of a sleeping beagle, drawn in {} style.",
        "A dog in a baseball uniform pitching a ball on a sandy field, illustrated in {} style.",
        "A beagle celebrating Thanksgiving with a plate of turkey and a pie, in {} style.",
        "A dog wearing goggles and a scarf, pretending to fly a plane, in {} style.",
        "A red doghouse with a beagle curled up on the roof under a starry sky, in {} style.",
        "A cartoon beagle holding a flower, presenting it to a small yellow bird, in {} style.",
        "A dog dressed as a lawyer, standing in a makeshift courtroom, in {} style.",
        "A beagle and its friends gathering around a Christmas tree in the snow, in {} style.",
        "A dog lying on its back, daydreaming about being a famous writer, in {} style.",
        "A red baron helmet sitting next to a sleeping beagle on its doghouse, in {} style.",
        "A cartoon beagle chasing a butterfly through a green meadow, in {} style.",
        "A dog holding a tray of cookies, offering them to its feathered friend, in {} style.",
        "A beagle in a detective outfit, solving a mystery in the neighborhood, in {} style.",
        "A doghouse decorated with Christmas lights, with a beagle peeking out, in {} style.",
        "A cartoon beagle playing a harmonica while sitting on a fence, in {} style.",
        "A dog wearing a crown, imagining itself as the king of the backyard, in {} style.",
        "A beagle and its owner sitting on a porch swing, enjoying a quiet evening, in {} style."
    ],
    "Mickey Mouse": [
        "A black mouse with large round ears wearing red shorts and white gloves, in {} style.",
        "A cartoon mouse steering a steamboat down a whistling river, rendered in {} style.",
        "A mouse in a sorcerer's hat, waving a wand to make brooms come alive, in {} style.",
        "A black mouse and his female companion dancing in a castle ballroom, in {} style.",
        "A mouse with big yellow shoes walking down Main Street, U.S.A., illustrated in {} style.",
        "A cartoon mouse holding a birthday cake with candles shaped like his ears, in {} style.",
        "A mouse in a tuxedo, conducting an orchestra of animated instruments, in {} style.",
        "A black mouse and his dog Pluto exploring a mysterious old house, in {} style.",
        "A mouse wearing a detective hat, solving a case in a rainy city alley, in {} style.",
        "A cartoon mouse flying a plane through fluffy white clouds, in {} style.",
        "A mouse with a red bow tie, hosting a clubhouse for his friends, in {} style.",
        "A black mouse and his friends riding a roller coaster at an amusement park, in {} style.",
        "A mouse in a cowboy outfit, riding a horse through the Wild West, in {} style.",
        "A cartoon mouse painting a rainbow with a giant brush, in {} style.",
        "A mouse holding a magic key, opening a door to a fantasy world, in {} style.",
        "A black mouse and his companion sharing a plate of spaghetti, in {} style.",
        "A mouse in a space suit, floating on the moon with a flag, in {} style.",
        "A cartoon mouse playing a guitar at a beach party with his friends, in {} style.",
        "A mouse wearing a crown, standing in front of a fairy-tale castle, in {} style.",
        "A black mouse and his friends decorating a Christmas tree with glowing ornaments, in {} style."
    ],
    "Spongebob": [
        "A yellow sea sponge wearing square pants and a red tie, flipping burgers in {} style.",
        "A sponge living in a pineapple house under the sea, rendered in {} style.",
        "A yellow sponge and his pink starfish friend blowing bubbles in the ocean, in {} style.",
        "A sponge working at a fast-food restaurant shaped like a crab, illustrated in {} style.",
        "A yellow sponge practicing karate with a squirrel in a spacesuit, in {} style.",
        "A sponge and his grumpy octopus neighbor trying to have a quiet day, in {} style.",
        "A yellow sponge catching jellyfish in a field with his net, in {} style.",
        "A sponge holding a delicious-looking burger with a secret recipe, in {} style.",
        "A yellow sponge and his starfish friend going on a treasure hunt, in {} style.",
        "A sponge working as a cashier at the Krusty Krab, in {} style.",
        "A yellow sponge riding a seahorse through the streets of Bikini Bottom, in {} style.",
        "A sponge and his friends having a party at the pineapple house, in {} style.",
        "A yellow sponge learning to drive a boatmobile from his driving teacher, in {} style.",
        "A sponge dressed as a superhero, saving Bikini Bottom from trouble, in {} style.",
        "A yellow sponge and his squirrel friend having a picnic in Jellyfish Fields, in {} style.",
        "A sponge making a giant Krabby Patty for a cooking contest, in {} style.",
        "A yellow sponge and his starfish friend building a sandcastle at the beach, in {} style.",
        "A sponge working late at the Krusty Krab, singing a song about burgers, in {} style.",
        "A yellow sponge and his friends watching a movie at the Bikini Bottom theater, in {} style.",
        "A sponge celebrating his birthday with a cake shaped like a Krabby Patty, in {} style."
    ],
    "Pikachu": [
        "A yellow mouse-like creature with a lightning bolt-shaped tail, in {} style.",
        "A small electric creature sitting on the shoulder of its trainer, rendered in {} style.",
        "A yellow creature releasing a powerful electric shock from its cheeks, in {} style.",
        "A small mouse-like creature being held in a red and white Poké Ball, illustrated in {} style.",
        "A yellow creature eating a bowl of ketchup with delight, in {} style.",
        "A small electric creature playing in a forest with other Pokémon, in {} style.",
        "A yellow creature wearing a red cap, just like its trainer's, in {} style.",
        "A small mouse-like creature battling against another Pokémon in a stadium, in {} style.",
        "A yellow creature napping in a patch of sunlight under a tree, in {} style.",
        "A small electric creature using its tail to light up a dark cave, in {} style.",
        "A yellow creature and its trainer walking along a dirt path on an adventure, in {} style.",
        "A small mouse-like creature holding a berry, offering it to a friend, in {} style.",
        "A yellow creature surrounded by sparkles as it uses a powerful move, in {} style.",
        "A small electric creature riding on a skateboard through a city park, in {} style.",
        "A yellow creature celebrating a victory by jumping up and down happily, in {} style.",
        "A small mouse-like creature wearing a cute costume for a Pokémon contest, in {} style.",
        "A yellow creature and its trainer sitting by a campfire, roasting marshmallows, in {} style.",
        "A small electric creature chasing a butterfly through a meadow of flowers, in {} style.",
        "A yellow creature using its electricity to charge a dead phone battery, in {} style.",
        "A small mouse-like creature hugging its trainer after a long day of adventures, in {} style."
    ],
    "Hello Kitty": [
        "A white cat with a red bow on her left ear, wearing a blue dress, in {} style.",
        "A cute white cat sitting at a table, enjoying afternoon tea with cake, rendered in {} style.",
        "A white cat with a yellow nose, holding a pink gift box tied with a ribbon, in {} style.",
        "A cute cat wearing a school uniform, carrying a red backpack, illustrated in {} style.",
        "A white cat and her twin sister Mimmy, wearing matching bows, in {} style.",
        "A cute white cat decorating a birthday cake with pink frosting, in {} style.",
        "A white cat sitting in a cozy room filled with pink furniture and stuffed animals, in {} style.",
        "A cute cat wearing a red dress, walking through a garden of roses, in {} style.",
        "A white cat holding a paintbrush, painting a picture of a rainbow, in {} style.",
        "A cute white cat and her friends having a picnic under a cherry blossom tree, in {} style.",
        "A white cat wearing a crown, pretending to be a princess in a castle, in {} style.",
        "A cute cat sitting on a windowsill, watching the rain fall outside, in {} style.",
        "A white cat holding a cup of hot chocolate, warming up by a fireplace, in {} style.",
        "A cute white cat wearing a Halloween costume, going trick-or-treating, in {} style.",
        "A white cat and her pet cat Charmmy Kitty, playing with a ball of yarn, in {} style.",
        "A cute white cat riding a pink bicycle through a park, in {} style.",
        "A white cat holding a bouquet of flowers, giving them to her mother, in {} style.",
        "A cute white cat wearing a kimono, celebrating a Japanese festival, in {} style.",
        "A white cat sitting at a piano, playing a beautiful melody, in {} style.",
        "A cute white cat and her friends having a sleepover with pillows and blankets, in {} style."
    ],
    "Van Gogh": [
        "Swirling night sky filled with stars and a glowing crescent moon, painted in {} style.",
        "A vase brimming with vibrant sunflowers against a warm yellow background, rendered in {} style.",
        "Golden wheat field with tall cypress trees swaying under a turbulent sky, in {} style.",
        "The bright yellow house with blue shutters on a sunny street in Arles, illustrated in {} style.",
        "Café terrace lit by warm gas lamps on a clear, starry night, painted in {} style.",
        "Self-portrait with a bandaged ear and a fur-lined hat, rendered in {} style.",
        "The Langlois Bridge at Arles with a woman crossing and water reflecting the sky, in {} style.",
        "Branches of an almond tree bursting with delicate pink blossoms against a blue sky, illustrated in {} style.",
        "A sower planting seeds in a plowed field at golden sunset, painted in {} style.",
        "A group of peasants sitting around a table eating potatoes by dim lamplight, rendered in {} style.",
        "Wheat field with black crows flying over a stormy, dark landscape, in {} style.",
        "The simple bedroom in Arles with bold, bright colors on the walls and furniture, illustrated in {} style.",
        "A cluster of purple irises growing in a garden with lush green foliage, painted in {} style.",
        "Tall, slender cypress trees reaching up toward a swirling, star-filled sky, rendered in {} style.",
        "The night café interior with billiard tables and warm, glowing overhead lights, in {} style.",
        "Portrait of Père Tanguy with a background of colorful Japanese prints, illustrated in {} style.",
        "Wheat field at sunset with golden hues and a winding path through the crops, painted in {} style.",
        "A garden filled with butterflies fluttering around bright, colorful flowers, rendered in {} style.",
        "Self-portrait wearing a straw hat and a light, casual jacket, in {} style.",
        "A rocky landscape with a small path and cypress trees under a dramatic, clouded sky, illustrated in {} style."
    ],
    "Picasso": [
        "Fragmented portrait of a woman with multiple overlapping perspectives, rendered in {} style.",
        "Cubist still life with a guitar, newspaper clippings, and a bottle of wine, painted in {} style.",
        "Monochromatic blue scene of a mother holding her child close in a quiet embrace, in {} style.",
        "Rose-colored depiction of a circus acrobat standing with a small, gentle horse, illustrated in {} style.",
        "Five women in bold, angular forms with masks and sharp, geometric lines, rendered in {} style.",
        "Peaceful dove carrying an olive branch in its beak, symbolizing hope, painted in {} style.",
        "Abstract, geometric depiction of a bull with fragmented horns and a muscular body, in {} style.",
        "Three musicians playing instruments in a cubist composition with bold, vibrant colors, illustrated in {} style.",
        "Woman standing before a mirror, her reflection showing a completely different perspective, rendered in {} style.",
        "Weeping woman with distorted features and tears streaming down her face in anguish, painted in {} style.",
        "Collage-style still life with pieces of newspaper, a guitar, and a glass of absinthe, in {} style.",
        "Seated woman in a relaxed pose, her form broken into sharp, geometric shapes, illustrated in {} style.",
        "Dreamlike portrait of a woman sleeping peacefully with soft, flowing forms around her, rendered in {} style.",
        "Blue period scene of an old, blind man holding a guitar, huddled in sadness, painted in {} style.",
        "Rose-colored depiction of a family of circus performers resting backstage after a show, in {} style.",
        "Cubist composition of a bull’s skull with sharp, angular fragments and bold lines, illustrated in {} style.",
        "Abstract deconstruction of a human face into overlapping planes and geometric shapes, rendered in {} style.",
        "The old guitarist sitting hunched over his instrument in deep, monochromatic blue, painted in {} style.",
        "Still life with a fruit bowl, a bottle, and a glass, all in cubist fragmentation, in {} style.",
        "Portrait of a woman with a bright flower in her hair, rendered in bold, cubist forms, illustrated in {} style."
    ],
    "Monet": [
        "Water lilies floating on a calm pond, their reflections blending with dappled sunlight, painted in {} style.",
        "Rouen Cathedral facade with shifting light and color across its rough stone surface, rendered in {} style.",
        "Haystack standing in a field, bathed in the warm, golden light of a rising sun, in {} style.",
        "Japanese bridge arching over a pond filled with water lilies and lush green foliage, illustrated in {} style.",
        "Vibrant garden in Giverny with colorful flowers, a winding path, and dappled sunlight through trees, painted in {} style.",
        "Sunrise over a quiet harbor, with soft, hazy light reflecting gently on the water, rendered in {} style.",
        "Houses of Parliament in London shrouded in thick, gray fog, with subtle hints of color peeking through, in {} style.",
        "Grand Canal in Venice, with beautiful buildings reflecting in the shimmering, turquoise water, illustrated in {} style.",
        "Row of tall poplar trees standing along a riverbank, their leaves catching the soft, golden light, painted in {} style.",
        "Field of bright red poppies with a few small figures walking through the blooms, rendered in {} style.",
        "Woman holding a white parasol, standing in a field with her young child beside her, in {} style.",
        "Group of women in a garden, surrounded by colorful flowers and soft, natural light, illustrated in {} style.",
        "Waves crashing against a rocky shore, with white foam and spray catching the bright sunlight, painted in {} style.",
        "Windmill in Amsterdam, with a calm canal and soft, diffused light in the air, rendered in {} style.",
        "Haystack covered in fresh snow, with cool, blue tones in the soft winter light, in {} style.",
        "Weeping willow tree with drooping branches, shrouded in gentle morning mist, illustrated in {} style.",
        "Rose garden in full bloom, with soft, pink petals and dappled light through the green leaves, painted in {} style.",
        "Beach scene with colorful umbrellas, people relaxing, and gentle waves lapping the shore, rendered in {} style.",
        "Boats floating quietly on the Seine River, with soft, hazy light and reflections on the water, in {} style.",
        "Irises growing in a garden bed, with rich purple and blue hues and soft, natural light, illustrated in {} style."
    ]
}

def remove_in_style(context_templates):
    new_templates = {}
    pattern = re.compile(r'(, )?in \{\} style\.\s*$')
    for k, v in context_templates.items():
        new_templates[k] = [pattern.sub('', s).strip() for s in v]
    return new_templates

context_templates_no_in_style = remove_in_style(context_templates)

if __name__ == "__main__":
    print(context_templates_no_in_style)
