imagenet_templates = [
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "a photo of a {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of a {}.",
    "a plushie {}.",
    "a photo of the nice {}.",
    "a photo of the small {}.",
    "a photo of the weird {}.",
    "the cartoon {}.",
    "art of the {}.",
    "a drawing of the {}.",
    "a photo of the large {}.",
    "a black and white photo of a {}.",
    "the plushie {}.",
    "a dark photo of a {}.",
    "itap of a {}.",
    "graffiti of the {}.",
    "a toy {}.",
    "itap of my {}.",
    "a photo of a cool {}.",
    "a photo of a small {}.",
    "a tattoo of the {}.",
]

imagenet_templates_extend = [
    "a hand-carved {}.",
    "a cast bronze {}.",
    "a needle-felted {}.",
    "a wood-carved {}.",
    "a leather-tooled {}.",
    "a paper-cut of a {}.",
    "a quilled {}.",
    "a resin-cast {}.",
    "a blown-glass {}.",
    "a fresco of a {}.",
    "a pastel drawing of a {}.",
    "a gouache painting of the {}.",
    "a linocut print of a {}.",
    "a woodblock print of the {}.",
    "a screen print of a {}.",
    "a lithograph of the {}.",
    "a monotype print of a {}.",
    "a spray-paint stencil of the {}.",
    "a collage of a {}.",
    "a mixed-media artwork of the {}.",
    "a bas-relief of a {}.",
    "a stained-glass depiction of the {}.",
    "a mosaic tile artwork of a {}.",
    "a silhouette of a {}.",
    "a stipple art drawing of the {}.",
    "a 3D rendered {}.",
    "a voxel art {}.",
    "a vector illustration of a {}.",
    "a procedurally generated {}.",
    "a game asset model of the {}.",
    "a VR model of a {}.",
    "a pixel sprite of the {}.",
    "a hologram of the {}.",
    "a 3D printed {}.",
    "a foam sculpted {}.",
    "a sand sculpture of a {}.",
    "an ice sculpture of the {}.",
    "a balloon twisted into a {}.",
    "a fondant model of the {}.",
    "a plush puppet of a {}.",
    "a bobblehead of the {}.",
    "a die-cast model of a {}.",
    "a paper mache {}.",
    "a metal forged {}.",
    "a chibi-style {}.",
    "a steampunk-themed {}.",
    "a cyberpunk-styled {}.",
    "a medieval tapestry depiction of a {}.",
    "a folk art styled {}.",
    "a storybook illustration of the {}.",
    "a fisheye photo of a {}.",
    "a wide-angle photo of the {}.",
    "a macro photo of a {}.",
    "a telephoto photo of the {}.",
    "a faded photo of a {}.",
    "a vintage photo of the {}.",
    "a retro photo of a {}.",
    "a filtered photo of the {}.",
    "an unedited photo of a {}.",
    "a professional photo of the {}.",
    "an amateur photo of a {}.",
    "a handheld photo of the {}.",
    "a studio photo of a {}.",
    "an outdoor photo of the {}.",
    "an indoor photo of a {}.",
    "a night photo of the {}.",
    "a daytime photo of a {}.",
]

painting_templates = [
    "{} style painting of the night sky with bold strokes.",
    "{} style landscape of rolling hills with dramatic brushwork.",
    "Self-portrait in {} style, showcasing distinctive color and texture.",
    "{} style rural scene with dynamic movement and intensity.",
    "Wheat field under a swirling sky in the style of {}.",
    "{} style transformation of simple cottages into profound scenes.",
    "{} style portrait conveying inner turmoil and vitality.",
    "Seascape in {} style capturing tumultuous waves and ocean movement.",
    "{} style depiction of light on water with delicate brushstrokes.",
    "Garden scene in {} style, emphasizing sunlight and shadow effects.",
    "{} style atmospheric haze enveloping the landscape.",
    "Haystacks in {} style, capturing light and color changes.",
    "Cathedral facade in {} style with shifting light and shadow.",
    "{} style vibrant flower garden in full bloom.",
    "{} style painting of boats as a study of color and atmosphere.",
    "{} style cliffs along the coastline with blended sea and sky.",
    "{} style bustling Paris streets with movement and vitality.",
    "Sunrise scene in {} style, capturing the beauty of dawn.",
    "{} style exploration of fog and mist in the landscape.",
    "Olive trees painted in {} style.",
    "Tree painted in {} style.",
    "Women working in the garden, in {} style.",
    "Wheat field painting by {}.",
    "Trees in bloom painted in {} style.",
    "{} style painting of a tree.",
    "Wheat field in {} style.",
    "{} style painting of a field with mountains in the background.",
    "Trees in bloom in the style of {}.",
    "Rocks in the ocean, in {} style.",
    "City painting in {} style.",
]

celebrity_templates = [
    "A portrait of {}.",
    "An image capturing {} at a public event.",
    "An oil painting of {}.",
    "A sketch of {}.",
    "{} in an official photo.",
    "{} smiling at the camera during a red carpet event.",
    "{} walking down the street in casual attire.",
    "A close-up of {} on stage during a live performance.",
    "{} posing for the paparazzi in a glamorous outfit.",
    "{} attending a movie premiere in a sleek suit.",
    "Candid shot of {} enjoying a day at the beach.",
    "{} giving an inspiring speech at a charity event.",
    "{} captured laughing during an interview.",
    "{} signing autographs for fans at a public appearance.",
    "A candid moment of {} sipping coffee at a café.",
    "{} performing on stage with a microphone in hand.",
    "A candid shot of {} waving at fans outside a venue.",
    "{} arriving at an award show in a stunning gown.",
    "{} enjoying a quiet moment reading a book.",
    "{} flashing a peace sign while posing for a selfie.",
    "A casual photo of {} walking a dog in the park.",
    "{} sitting in the front row of a fashion show.",
    "A behind-the-scenes shot of {} getting ready for a shoot.",
    "{} walking the runway at a fashion show.",
    "{} dancing on stage at a live concert."
]

template_dict = {
    'instance': imagenet_templates,
    'style': painting_templates,
    'celebrity': celebrity_templates,
}
